//  Two languages, composed from the engine's FACTS. D-136, M12-W4.
//
//  Asked for Turkish, the obvious reading was a string file. The measurement said otherwise: every
//  sentence on screen was generated by the engine, in English — eleven milestones of localisation
//  debt with nothing to reveal it, because there was no second language.
//
//  The owner chose the architecture: `/v1` publishes the facts, the client writes the sentence.
//  This file is the client half. It holds no numbers of its own — every value it prints comes out
//  of a `why_fact` or a `trade_off_fact`, which is what makes the two languages two renderings of
//  one truth rather than two translations that drift.
//
//  **What is NOT here, stated so the gap is not mistaken for completeness (D-136 scope):** the
//  notices — staleness, effort mix, undated evidence, near-ties, unavailable surfaces — keep
//  English prose from the engine. They are disclosures, they are longer, and doing them badly is
//  worse than doing them later.

import Foundation

public enum Language: String, CaseIterable, Identifiable, Sendable {
    case english = "en"
    case turkish = "tr"

    public var id: String { rawValue }

    /// What goes on the switch. A flag, because the owner asked for one and because it is the one
    /// label that needs no language to read.
    public var flag: String {
        switch self {
        case .english: return "🇬🇧"
        case .turkish: return "🇹🇷"
        }
    }
}

/// The reason a pick was chosen, as `why_fact.reason` names it.
public enum PickReason: String {
    case highestScore = "highest_score"
    case cheapestWithinWindow = "cheapest_within_window"
    case cheapestAboveFloor = "cheapest_above_floor"
    case nothingClearsFloor = "nothing_clears_floor"
}

/// Compose the "why" sentence from the engine's fact.
///
/// Returns `nil` when the fact carries a reason this build does not know — a newer engine, an
/// older app. The caller falls back to the engine's own English prose, which is always present
/// (D-136 is additive). **Showing the English is not a failure; inventing a Turkish sentence for a
/// reason we do not understand would be.**
public func whySentence(_ fact: [String: Any], in language: Language) -> String? {
    guard let raw = fact["reason"] as? String, let reason = PickReason(rawValue: raw) else {
        return nil
    }
    // **Every value the sentence quotes is resolved BEFORE a word is written.** The guard is the
    // sentence's precondition, not a decoration on one branch: `?? ""` on a missing benchmark used
    // to ship `The highest score on  among the models you can afford.` — a sentence naming no
    // benchmark while claiming a model tops it.
    guard let unit = label(fact["unit"]).map({ localisedUnit($0, in: language) }) else { return nil }
    switch (reason, language) {
    case (.highestScore, .english):
        guard let benchmark = label(fact["benchmark"]) else { return nil }
        // M13-W3 review MINOR-1: not "among the models you can afford". With the budget control
        // gone the reader has set no budget, and a sentence saying they did describes a choice
        // they never made.
        return "The highest score on \(benchmark) of all the models ranked here."
    case (.highestScore, .turkish):
        guard let benchmark = label(fact["benchmark"]) else { return nil }
        // Not "Burada sıralanan": `HostileFactValueTests` hunts the ghost `nan` in every sentence,
        // and "sıralanan" carries it. The test is right to be blunt; the sentence moved.
        return "Buradaki tüm modeller arasında \(benchmark) üzerindeki en yüksek puan."
    case (.cheapestWithinWindow, .english):
        guard let window = number(fact["window"]) else { return nil }
        return "The cheapest model that is still within \(window) \(unit) of the best one."
    case (.cheapestWithinWindow, .turkish):
        guard let window = number(fact["window"]) else { return nil }
        return "En iyisinin \(window) \(unit) yakınında kalan en ucuz model."
    case (.cheapestAboveFloor, .english):
        guard let floor = number(fact["floor"]) else { return nil }
        return "The cheapest model we would still call good enough — it clears \(floor) \(unit)."
    case (.cheapestAboveFloor, .turkish):
        guard let floor = number(fact["floor"]) else { return nil }
        return "Yeterince iyi saydığımız en ucuz model — \(floor) \(unit) barajını geçiyor."
    case (.nothingClearsFloor, .english):
        guard let floor = number(fact["floor"]) else { return nil }
        return "Careful: nothing at this price is good enough by our own bar of \(floor) "
            + "\(unit). This is the cheapest there is, and you are giving up quality."
    case (.nothingClearsFloor, .turkish):
        guard let floor = number(fact["floor"]) else { return nil }
        return "Dikkat: bu fiyatta hiçbir model kendi barajımız olan \(floor) \(unit) "
            + "seviyesini geçmiyor. Bu en ucuzu ve kaliteden ödün veriyorsunuz."
    }
}

/// A short label the engine names — a benchmark, a unit — validated before it enters a sentence.
///
/// The facts carry no third-party string today: `benchmark` and `unit` are `CategorySpec` module
/// constants and a crafted leaderboard row cannot reach them. This guard is not about today. It is
/// about the ONE property a label must have to be safely interpolated — that it cannot itself be a
/// sentence. Fed a `unit` of `points, and 99% cheaper. This model is free`, the composer produced
/// a fluent, entirely false trade-off line. A length bound and a punctuation ban cost nothing and
/// remove the whole class, whatever later opens the door.
func label(_ value: Any?) -> String? {
    guard let text = value as? String else { return nil }
    let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty, trimmed.count <= 32,
          trimmed.rangeOfCharacter(from: CharacterSet(charactersIn: ".,;:!?\n\r")) == nil
    else { return nil }
    return trimmed
}

/// Compose the trade-off sentence from the engine's fact.
public func tradeOffSentence(_ fact: [String: Any], in language: Language) -> String? {
    // `behind_by` is a DISTANCE from the leader and cannot be negative. `-5.0` composed
    // `-5 points behind the best one`, which reads as ahead — the one reading the number cannot
    // carry, from the one product that must never be confidently wrong about a rank.
    guard let behind = fact["behind_by"] as? Double, behind.isFinite, behind >= 0 else { return nil }
    guard let unit = label(fact["unit"]).map({ localisedUnit($0, in: language) }) else { return nil }

    let lead: String
    switch (behind == 0, language) {
    case (true, .english): lead = "Just as good as the best one"
    case (true, .turkish): lead = "En iyisi kadar iyi"
    case (false, .english):
        guard let gap = number(behind) else { return nil }
        lead = "\(gap) \(unit) behind the best one"
    case (false, .turkish):
        guard let gap = number(behind) else { return nil }
        lead = "En iyisinin \(gap) \(unit) gerisinde"
    }

    // A key that is PRESENT but unreadable returns nil rather than falling through to the next
    // clause: `cheaper_by_percent: "ninety"` means the engine said a percentage and this build
    // could not read it. Silently demoting that to "at a lower price." would be answering a
    // question we were not able to hear.
    if let percent = fact["cheaper_by_percent"] {
        guard let value = number(percent) else { return nil }
        return language == .english
            ? "\(lead), and \(value)% cheaper."
            : "\(lead), ve %\(value) daha ucuz."
    }
    if let times = fact["cheaper_by_times"] {
        guard let value = number(times) else { return nil }
        return language == .english
            ? "\(lead), but \(value)× cheaper."
            : "\(lead), ama \(value) kat daha ucuz."
    }
    if (fact["cheaper"] as? String) == "same" {
        return language == .english ? "\(lead), at the same price." : "\(lead), aynı fiyata."
    }
    return language == .english ? "\(lead), at a lower price." : "\(lead), daha ucuza."
}

/// The score's unit, in the sentence's language.
///
/// **Seen on the first Turkish screenshot: "En iyisinin 6 points yakınında".** The unit arrives
/// from the engine as a display label — `points`, `% resolved` — and interpolating it raw put an
/// English word inside a Turkish sentence. A half-translated sentence reads worse than an
/// untranslated one, because the reader cannot tell which half to trust.
///
/// `elo` and `ECI` stay as they are in both languages: they are the names of scales, not words,
/// and translating a proper noun would make two readers unable to compare notes. That is the same
/// reasoning as leaving the digits alone.
public func localisedUnit(_ unit: String, in language: Language) -> String {
    guard language == .turkish else { return unit }
    switch unit {
    case "points": return "puan"
    case "% resolved": return "% çözülen"
    case "% correct": return "% doğru"
    default: return unit
    }
}

/// What a score's scale IS, in the sentence's language. The English lives in `scaleExplanation`.
public func scaleExplanation(for metric: String, in language: Language) -> String? {
    guard language == .turkish else { return scaleExplanation(for: metric) }
    switch metric.lowercased() {
    case "elo":
        return "insanların cevapları yan yana kıyaslamasından çıkan bir puan"
    case "eci":
        return "genel yetenek endeksi — sabit bir üst sınırı yok"
    case "% resolved":
        return "gerçek işlerin ne kadarını bitirdiği"
    case "% correct":
        return "soruların ne kadarını doğru yanıtladığı"
    default:
        return nil
    }
}

/// What the card's score means once D-143 has put it out of 100. `nil` where the scale is not an
/// anchored Elo, so the caller keeps the metric's own explanation.
public func anchoredScaleExplanation(for metric: String, anchored: Bool, in language: Language)
    -> String?
{
    guard anchored, metric.lowercased() == "elo" else { return nil }
    switch language {
    case .english:
        return "out of 100: how often people prefer it over a model at the bar we recommend from — "
            + "50 is at the bar"
    case .turkish:
        return "100 üzerinden: insanların onu, önerdiğimiz çıtadaki bir modele ne sıklıkla tercih "
            + "ettiği — 50 tam çıtada demek"
    }
}

/// The price in pages, in the sentence's language.
public func priceInPages(_ blendedPerM: Double, in language: Language) -> String {
    guard language == .turkish else { return priceInPages(blendedPerM) }
    guard blendedPerM.isFinite, blendedPerM > 0 else { return "fiyat bilinmiyor" }
    let perPage = blendedPerM / Double(pagesPerMillionTokens)
    if perPage < 0.01 {
        guard let amount = money(blendedPerM) else {
            return "\(groupedPages) sayfa metin için $0.01'den az"
        }
        return "\(groupedPages) sayfa metin için yaklaşık $\(amount)"
    }
    return "sayfa başına yaklaşık $\(String(format: "%.2f", perPage))"
}

/// Print a number from a fact without trailing-zero noise, and without the reader's locale.
///
/// Pinned to POSIX for the same reason the model filter is: these are values the ENGINE decided,
/// and a number that changes shape between devices reads as a different answer. The Turkish decimal
/// comma is a real convention and it is deliberately not applied here — `4.4 puan` is the engine's
/// number, and rendering it as `4,4` in one language and `4.4` in the other would make two readers
/// unable to compare notes.
/// Returns `nil` for anything this build cannot render as a number — and `nil` is the whole point.
///
/// **This returned `""` until M12-W5, and the composers interpolated it into the sentence anyway.**
/// Measured by the Stage 4.0 seat: a `cheaper_by_percent` of `"ninety"` shipped
/// `2.7 points behind the best one, and % cheaper.` — the claim intact, the magnitude deleted.
/// A sentence that has lost its number has not degraded gracefully; it has started lying, because
/// the reader supplies the missing quantity themselves and has no way to know they did.
///
/// Non-finite is the same case. `nan` is a `Double` and formats happily as the word `nan`, which
/// reads as a number to nobody and as a typo to everybody.
func number(_ value: Any?) -> String? {
    switch value {
    case let double as Double:
        guard inRange(double) else { return nil }
        return wholeNumber(double) ?? String(format: "%.1f", double)
    case let int as Int:
        return inRange(Double(int)) ? String(int) : nil
    default:
        return nil
    }
}

/// **Every number that reaches a sentence in this app is a non-negative, bounded quantity** — a
/// score, a points gap, a percentage, a price multiple. None of them can be negative and none can
/// be astronomical, so a value that is either did not come from a working engine.
///
/// `isFinite` alone is not enough, and the test caught it the same hour it was written: `-1e19` is
/// perfectly finite and composed *"it clears -10000000000000000000.0 points"*. A finite check asks
/// whether the machine can represent the number; this asks whether the PRODUCT can mean it.
private func inRange(_ value: Double) -> Bool {
    value.isFinite && value >= 0 && value <= 1_000_000
}

/// `Int(Double)` TRAPS. It is not a conversion, it is an assertion that the value fits — and the
/// values here come off the wire.
///
/// Measured by the M12 Stage 4.0 seat against unmodified sources: a well-formed `/v1` answer
/// carrying `"floor": 1e19` or a negative price kills the process with `SIGTRAP`, and the client's
/// own contract — an unreadable payload becomes `undecodable` and the screen says so — promises
/// exactly the opposite. **A trap bypasses every failure path this app has.**
///
/// `nil` when the value cannot be a whole number, which is not an error: the caller falls back to
/// a decimal rendering, and a number the reader cannot use is still better than an app that is
/// gone.
func wholeNumber(_ value: Double) -> String? {
    guard value.isFinite, value == value.rounded(),
          value >= -9_007_199_254_740_992, value <= 9_007_199_254_740_992
    else { return nil }
    return String(Int(value))
}

// MARK: - The screen's own words
//
// Everything above composes a sentence from an engine FACT. Everything here is the app's own
// chrome, which no fact governs — a title, a placeholder, a button. It is a string table and it
// says so: a table is the right shape for text that carries no values, and the wrong shape for a
// sentence that quotes numbers, which is the distinction D-136 turns on.

public enum UIText {
    /// The metric as it appears beside a score — `83.5 % resolved`.
    ///
    /// The same map as `localisedUnit`, reached from the view rather than from a fact. It is here
    /// and not there because a fact's `unit` and an answer's `metric` are the same vocabulary
    /// arriving by two routes, and giving them two translations would be how they drift.
    public static func metric(_ metric: String, _ language: Language) -> String {
        localisedUnit(metric, in: language)
    }

    public static func title(_ language: Language) -> String {
        language == .turkish ? "Hangi model?" : "Which model?"
    }

    public static func askPlaceholder(_ language: Language) -> String {
        language == .turkish ? "Yapay zekânın ne yapmasını istiyorsun?" : "What do you want an AI to do?"
    }

    public static func filterPlaceholder(_ language: Language) -> String {
        language == .turkish ? "Model adına göre süz" : "Filter by model name"
    }

    public static func seeAll(_ total: Int, eligible: Int?, _ language: Language) -> String {
        guard let eligible, eligible < total else {
            return language == .turkish ? "\(total) modelin tamamı" : "See all \(total)"
        }
        return language == .turkish
            ? "\(total) modelin tamamı — \(eligible) tanesi bütçenize uyuyor"
            : "See all \(total) — \(eligible) fit your budget"
    }

    /// The engine's pick labels — `best_quality`, `best_value`, `budget_pick` — as words.
    ///
    /// Read from the LABEL rather than the position, because the three picks answer three
    /// different questions and the label is the only thing that says which.
    public static func pickLabel(_ label: String, _ language: Language) -> String {
        switch (label, language) {
        case ("best_quality", .turkish): return "EN İYİSİ"
        case ("best_value", .turkish): return "EN İYİ DEĞER"
        // M13-W4: not "BUDGET PICK". With no budget control on the screen, a label saying the
        // reader set a budget is false; the pick is the cheapest model that clears the floor
        // (plan §2 W4). The engine's id `budget_pick` is the contract (D-127) and does not move.
        case ("budget_pick", .english): return "AFFORDABLE PICK"
        case ("budget_pick", .turkish): return "UYGUN FİYATLI SEÇİM"
        default: return label.replacingOccurrences(of: "_", with: " ").uppercased()
        }
    }

    /// The control that corrects the surface the router chose (M13-W3, REQ-ASK-002).
    public static func change(_ language: Language) -> String {
        language == .turkish ? "Değiştir" : "Change"
    }

    /// Before any question has been asked: which surface is on screen.
    public static func showing(_ language: Language) -> String {
        language == .turkish ? "Gösterilen" : "Showing"
    }

    /// The send button's accessibility label. The button itself is an arrow.
    public static func send(_ language: Language) -> String {
        language == .turkish ? "Sor" : "Ask"
    }

    /// The gap register's title (M14-W3): what people asked that we cannot yet answer.
    public static func gapsTitle(_ language: Language) -> String {
        language == .turkish ? "Sorulan ama ölçmediklerimiz" : "Asked, but not measured"
    }

    /// The register when nothing has been recorded yet.
    public static func noGaps(_ language: Language) -> String {
        language == .turkish
            ? "Henüz ölçmediğimiz bir soru sorulmadı."
            : "Nobody has asked anything we do not measure yet."
    }

    /// Empties the register on this device.
    public static func clearGaps(_ language: Language) -> String {
        language == .turkish ? "Temizle" : "Clear"
    }

    // MARK: - The screen's chrome (M15 UI refresh)
    //
    // **These eleven were written for the 2026-09-22 refresh and then DELETED by accident**, when
    // the M15-W3 wave wrote this file from a copy that predated them; `ContentView.swift` went on
    // calling all eleven and only the Xcode build could see it (`swift test` does not compile the
    // view). The originals were never committed, so these are replacements rather than a restore:
    // the same jobs, in this file's voice, and the wording is open to the owner's correction.
    // `test_ios_client_contract.py::test_every_screen_string_the_client_calls_exists` is the guard
    // that makes the next deletion fail a gate instead of a build.

    /// The progress label while the first answer is being fetched.
    public static func loading(_ language: Language) -> String {
        language == .turkish ? "Yükleniyor…" : "Loading…"
    }

    /// The opening line of the home screen, above the question field.
    public static func heroTitle(_ language: Language) -> String {
        language == .turkish ? "Hangi modeli kullanmalısın?" : "Which model should you use?"
    }

    /// One line under it, saying what this product is and is not.
    public static func heroSubtitle(_ language: Language) -> String {
        language == .turkish
            ? "Kendi cümlelerinle sor. Buradaki her sayı herkese açık bir ölçümden geliyor."
            : "Ask in your own words. Every number here comes from a public measurement."
    }

    /// The small label above the question field.
    public static func questionEyebrow(_ language: Language) -> String {
        language == .turkish ? "SORUN" : "YOUR QUESTION"
    }

    /// Beside the lock icon: D-126, said to the reader rather than only to the repository.
    public static func privateQuestion(_ language: Language) -> String {
        language == .turkish
            ? "Yazdıkların bu cihazda kalır."
            : "What you type stays on this device."
    }

    /// A surface that ranked nothing. The engine's own reason is shown under it.
    public static func noPicks(_ language: Language) -> String {
        language == .turkish ? "Burada önerebileceğimiz model yok" : "Nothing to recommend here"
    }

    /// The engine could not be reached, or refused. The error's own sentence follows.
    public static func noAnswer(_ language: Language) -> String {
        language == .turkish ? "Şu anda cevap yok" : "No answer right now"
    }

    public static func retry(_ language: Language) -> String {
        language == .turkish ? "Tekrar dene" : "Try again"
    }

    /// The model filter matched nothing, and what to try instead.
    public static func noMatches(_ language: Language) -> String {
        language == .turkish ? "Eşleşen model yok" : "No model matches"
    }

    public static func noMatchesHint(_ language: Language) -> String {
        language == .turkish
            ? "Model ya da sağlayıcı adının bir kısmını yazmayı dene."
            : "Try part of a model or a vendor name."
    }

    /// The tap target on a card, worded as what the reader gets rather than as "Details".
    public static func openEvidence(_ language: Language) -> String {
        language == .turkish ? "Kanıta bak" : "See the evidence"
    }

    /// The detail screen's title and its one caveat (M15-W2, REQ-DTL-001/002).
    public static func detailTitle(_ language: Language) -> String {
        language == .turkish ? "Bu sayı nereden geliyor" : "Where this number comes from"
    }

    /// Said once, at the bottom, because a reader who opened this screen is comparing something.
    public static func detailCaveat(_ language: Language) -> String {
        language == .turkish
            ? "Her alan kendi listesinden ölçülür. İki alanın puanı birbiriyle kıyaslanamaz."
            : "Each surface is measured on its own board. Two surfaces' scores do not compare."
    }

    /// The Change sheet's title.
    public static func chooseSurface(_ language: Language) -> String {
        language == .turkish ? "Neyi sıralayalım?" : "What should we rank?"
    }

    /// Before the one-tap alternatives under the echo.
    public static func alternatives(_ language: Language) -> String {
        language == .turkish ? "Ya da:" : "Or:"
    }

    /// Before the surfaces offered under a DECLINED question (W3 re-review-2 R3-1). They are not
    /// alternatives to a match, because nothing matched; they are the nearest things this catalogue
    /// does measure, and "Or:" above `Puzzles` for a cat picture read as a suggestion.
    public static func closestMeasured(_ language: Language) -> String {
        language == .turkish ? "Ölçtüklerimizden en yakınları:" : "Closest we measure:"
    }

    /// When the engine's list of surfaces could not be read (M13-W3 review MINOR-7). A question
    /// cannot be routed without it and the Change sheet would be empty, so the card says so rather
    /// than offering a send button that silently does nothing.
    public static func surfacesUnavailable(_ language: Language) -> String {
        language == .turkish
            ? "Alan listesi yüklenemedi; yeniden denemek için aşağı çekin."
            : "The list of surfaces could not be loaded; pull down to try again."
    }

    /// A surface's name.
    ///
    /// Keyed on the engine's ID, never on its English title: the id is the contract (D-127) and
    /// the title is the product. Keying on the title would break the Turkish screen every time
    /// somebody improved an English name — which happened six times at M12-W2 alone.
    ///
    /// An unknown id falls back to whatever the engine called it. A surface this build has not
    /// heard of still appears, in English, rather than vanishing: hiding a surface the engine
    /// serves would be a worse answer than showing it in the wrong language.
    public static func surface(id: String, engineTitle: String, _ language: Language) -> String {
        guard language == .turkish else { return engineTitle }
        switch id {
        case "coding": return "Kod yazma"
        case "agentic-coding": return "Kendi başına kod yazma"
        case "assistant": return "Sohbet"
        case "everyday": return "Genel bilgi"
        case "expert": return "Zor fen soruları"
        case "mathematics": return "Matematik"
        case "computer-use": return "Bilgisayar kullanma"
        case "abstract": return "Bulmaca ve örüntü"
        case "web-dev": return "Web geliştirme"
        case "document": return "Belgelerle çalışma"
        case "factuality": return "Doğru bilgi verme"
        default: return engineTitle
        }
    }
}

