//  Two languages, composed from the engine's FACTS. D-136, M12-W4.
//
//  Asked for Turkish, the obvious reading was a string file. The measurement said otherwise: every
//  sentence on screen was generated by the engine, in English — eleven milestones of localisation
//  debt with nothing to reveal it, because there was no second language.
//
//  The owner chose the architecture: `/v1` publishes the facts, the client writes the sentence.
//  This file is the client half. It holds no numbers of its own — every value it prints comes out
//  of a `why_fact` or a `trade_off_fact`, which is what makes the two languages two renderings of
//  one truth rather than two translations that drift.
//
//  **What is NOT here, stated so the gap is not mistaken for completeness (D-136 scope):** the
//  notices — staleness, effort mix, undated evidence, near-ties, unavailable surfaces — keep
//  English prose from the engine. They are disclosures, they are longer, and doing them badly is
//  worse than doing them later.

import Foundation

public enum Language: String, CaseIterable, Identifiable, Sendable {
    case english = "en"
    case turkish = "tr"

    public var id: String { rawValue }

    /// What goes on the switch. A flag, because the owner asked for one and because it is the one
    /// label that needs no language to read.
    public var flag: String {
        switch self {
        case .english: return "🇬🇧"
        case .turkish: return "🇹🇷"
        }
    }
}

/// The reason a pick was chosen, as `why_fact.reason` names it.
public enum PickReason: String {
    case highestScore = "highest_score"
    case cheapestWithinWindow = "cheapest_within_window"
    case cheapestAboveFloor = "cheapest_above_floor"
    case nothingClearsFloor = "nothing_clears_floor"
}

/// Compose the "why" sentence from the engine's fact.
///
/// Returns `nil` when the fact carries a reason this build does not know — a newer engine, an
/// older app. The caller falls back to the engine's own English prose, which is always present
/// (D-136 is additive). **Showing the English is not a failure; inventing a Turkish sentence for a
/// reason we do not understand would be.**
public func whySentence(_ fact: [String: Any], in language: Language) -> String? {
    guard let raw = fact["reason"] as? String, let reason = PickReason(rawValue: raw) else {
        return nil
    }
    let unit = localisedUnit(fact["unit"] as? String ?? "", in: language)
    switch (reason, language) {
    case (.highestScore, .english):
        let benchmark = fact["benchmark"] as? String ?? ""
        return "The highest score on \(benchmark) among the models you can afford."
    case (.highestScore, .turkish):
        let benchmark = fact["benchmark"] as? String ?? ""
        return "Bütçenize uyan modeller arasında \(benchmark) üzerindeki en yüksek puan."
    case (.cheapestWithinWindow, .english):
        return "The cheapest model that is still within \(number(fact["window"])) \(unit) "
            + "of the best one."
    case (.cheapestWithinWindow, .turkish):
        return "En iyisinin \(number(fact["window"])) \(unit) yakınında kalan en ucuz model."
    case (.cheapestAboveFloor, .english):
        return "The cheapest model we would still call good enough — it clears "
            + "\(number(fact["floor"])) \(unit)."
    case (.cheapestAboveFloor, .turkish):
        return "Yeterince iyi saydığımız en ucuz model — \(number(fact["floor"])) \(unit) "
            + "barajını geçiyor."
    case (.nothingClearsFloor, .english):
        return "Careful: nothing at this price is good enough by our own bar of "
            + "\(number(fact["floor"])) \(unit). This is the cheapest there is, and you are "
            + "giving up quality."
    case (.nothingClearsFloor, .turkish):
        return "Dikkat: bu fiyatta hiçbir model kendi barajımız olan \(number(fact["floor"])) "
            + "\(unit) seviyesini geçmiyor. Bu en ucuzu ve kaliteden ödün veriyorsunuz."
    }
}

/// Compose the trade-off sentence from the engine's fact.
public func tradeOffSentence(_ fact: [String: Any], in language: Language) -> String? {
    guard let behind = fact["behind_by"] as? Double else { return nil }
    let unit = localisedUnit(fact["unit"] as? String ?? "", in: language)

    let lead: String
    switch (behind == 0, language) {
    case (true, .english): lead = "Just as good as the best one"
    case (true, .turkish): lead = "En iyisi kadar iyi"
    case (false, .english): lead = "\(number(behind)) \(unit) behind the best one"
    case (false, .turkish): lead = "En iyisinin \(number(behind)) \(unit) gerisinde"
    }

    if let percent = fact["cheaper_by_percent"] {
        return language == .english
            ? "\(lead), and \(number(percent))% cheaper."
            : "\(lead), ve %\(number(percent)) daha ucuz."
    }
    if let times = fact["cheaper_by_times"] {
        return language == .english
            ? "\(lead), but \(number(times))× cheaper."
            : "\(lead), ama \(number(times)) kat daha ucuz."
    }
    if (fact["cheaper"] as? String) == "same" {
        return language == .english ? "\(lead), at the same price." : "\(lead), aynı fiyata."
    }
    return language == .english ? "\(lead), at a lower price." : "\(lead), daha ucuza."
}

/// The score's unit, in the sentence's language.
///
/// **Seen on the first Turkish screenshot: "En iyisinin 6 points yakınında".** The unit arrives
/// from the engine as a display label — `points`, `% resolved` — and interpolating it raw put an
/// English word inside a Turkish sentence. A half-translated sentence reads worse than an
/// untranslated one, because the reader cannot tell which half to trust.
///
/// `elo` and `ECI` stay as they are in both languages: they are the names of scales, not words,
/// and translating a proper noun would make two readers unable to compare notes. That is the same
/// reasoning as leaving the digits alone.
public func localisedUnit(_ unit: String, in language: Language) -> String {
    guard language == .turkish else { return unit }
    switch unit {
    case "points": return "puan"
    case "% resolved": return "% çözülen"
    case "% correct": return "% doğru"
    default: return unit
    }
}

/// What a score's scale IS, in the sentence's language. The English lives in `scaleExplanation`.
public func scaleExplanation(for metric: String, in language: Language) -> String? {
    guard language == .turkish else { return scaleExplanation(for: metric) }
    switch metric.lowercased() {
    case "elo":
        return "insanların cevapları yan yana kıyaslamasından çıkan bir puan"
    case "eci":
        return "genel yetenek endeksi — sabit bir üst sınırı yok"
    case "% resolved":
        return "gerçek işlerin ne kadarını bitirdiği"
    case "% correct":
        return "soruların ne kadarını doğru yanıtladığı"
    default:
        return nil
    }
}

/// The price in pages, in the sentence's language.
public func priceInPages(_ blendedPerM: Double, in language: Language) -> String {
    guard language == .turkish else { return priceInPages(blendedPerM) }
    let perPage = blendedPerM / Double(pagesPerMillionTokens)
    if perPage < 0.01 {
        return "\(groupedPages) sayfa metin için yaklaşık $\(Int(blendedPerM.rounded()))"
    }
    return "sayfa başına yaklaşık $\(String(format: "%.2f", perPage))"
}

/// Print a number from a fact without trailing-zero noise, and without the reader's locale.
///
/// Pinned to POSIX for the same reason the model filter is: these are values the ENGINE decided,
/// and a number that changes shape between devices reads as a different answer. The Turkish decimal
/// comma is a real convention and it is deliberately not applied here — `4.4 puan` is the engine's
/// number, and rendering it as `4,4` in one language and `4.4` in the other would make two readers
/// unable to compare notes.
func number(_ value: Any?) -> String {
    switch value {
    case let double as Double:
        return double == double.rounded()
            ? String(Int(double))
            : String(format: "%.1f", double)
    case let int as Int:
        return String(int)
    default:
        return ""
    }
}

// MARK: - The screen's own words
//
// Everything above composes a sentence from an engine FACT. Everything here is the app's own
// chrome, which no fact governs — a title, a placeholder, a button. It is a string table and it
// says so: a table is the right shape for text that carries no values, and the wrong shape for a
// sentence that quotes numbers, which is the distinction D-136 turns on.

public enum UIText {
    /// The metric as it appears beside a score — `83.5 % resolved`.
    ///
    /// The same map as `localisedUnit`, reached from the view rather than from a fact. It is here
    /// and not there because a fact's `unit` and an answer's `metric` are the same vocabulary
    /// arriving by two routes, and giving them two translations would be how they drift.
    public static func metric(_ metric: String, _ language: Language) -> String {
        localisedUnit(metric, in: language)
    }

    public static func title(_ language: Language) -> String {
        language == .turkish ? "Hangi model?" : "Which model?"
    }

    public static func askPlaceholder(_ language: Language) -> String {
        language == .turkish ? "Yapay zekânın ne yapmasını istiyorsun?" : "What do you want an AI to do?"
    }

    public static func filterPlaceholder(_ language: Language) -> String {
        language == .turkish ? "Model adına göre süz" : "Filter by model name"
    }

    public static func seeAll(_ total: Int, eligible: Int?, _ language: Language) -> String {
        guard let eligible, eligible < total else {
            return language == .turkish ? "\(total) modelin tamamı" : "See all \(total)"
        }
        return language == .turkish
            ? "\(total) modelin tamamı — \(eligible) tanesi bütçenize uyuyor"
            : "See all \(total) — \(eligible) fit your budget"
    }

    /// The engine's pick labels — `best_quality`, `best_value`, `budget_pick` — as words.
    ///
    /// Read from the LABEL rather than the position, because the three picks answer three
    /// different questions and the label is the only thing that says which.
    public static func pickLabel(_ label: String, _ language: Language) -> String {
        switch (label, language) {
        case ("best_quality", .turkish): return "EN İYİSİ"
        case ("best_value", .turkish): return "EN İYİ DEĞER"
        case ("budget_pick", .turkish): return "BÜTÇE SEÇİMİ"
        default: return label.replacingOccurrences(of: "_", with: " ").uppercased()
        }
    }

    /// A budget button's words.
    public static func budget(_ id: String, _ language: Language) -> String {
        switch (id, language) {
        case ("low", .turkish): return "Daha ucuz"
        case ("medium", .turkish): return "Orta"
        case ("unlimited", .turkish): return "Fiyat farketmez"
        default: return BudgetOption(id: id, blendedCapPerM: nil).title
        }
    }

    /// A surface's name.
    ///
    /// Keyed on the engine's ID, never on its English title: the id is the contract (D-127) and
    /// the title is the product. Keying on the title would break the Turkish screen every time
    /// somebody improved an English name — which happened six times at M12-W2 alone.
    ///
    /// An unknown id falls back to whatever the engine called it. A surface this build has not
    /// heard of still appears, in English, rather than vanishing: hiding a surface the engine
    /// serves would be a worse answer than showing it in the wrong language.
    public static func surface(id: String, engineTitle: String, _ language: Language) -> String {
        guard language == .turkish else { return engineTitle }
        switch id {
        case "coding": return "Kod yazma"
        case "agentic-coding": return "Kendi başına kod yazma"
        case "assistant": return "Sohbet"
        case "everyday": return "Genel bilgi"
        case "expert": return "Zor fen soruları"
        case "mathematics": return "Matematik"
        case "computer-use": return "Bilgisayar kullanma"
        case "abstract": return "Bulmaca ve örüntü"
        case "web-dev": return "Web geliştirme"
        default: return engineTitle
        }
    }
}

