//  Two languages, composed from the engine's FACTS. D-136, M12-W4.
//
//  Asked for Turkish, the obvious reading was a string file. The measurement said otherwise: every
//  sentence on screen was generated by the engine, in English — eleven milestones of localisation
//  debt with nothing to reveal it, because there was no second language.
//
//  The owner chose the architecture: `/v1` publishes the facts, the client writes the sentence.
//  This file is the client half. It holds no numbers of its own — every value it prints comes out
//  of a `why_fact` or a `trade_off_fact`, which is what makes the two languages two renderings of
//  one truth rather than two translations that drift.
//
//  The notices — staleness, effort mix, undated evidence, near-ties, unavailable surfaces — were
//  D-136's recorded remainder and kept the engine's English until M18-W2. They are composed in
//  `Notices.swift` now, from facts, the same way (D-176).

import Foundation

public enum Language: String, CaseIterable, Identifiable, Sendable {
    case english = "en"
    case turkish = "tr"

    public var id: String { rawValue }

    /// What goes on the switch. A flag, because the owner asked for one and because it is the one
    /// label that needs no language to read.
    public var flag: String {
        switch self {
        case .english: return "🇬🇧"
        case .turkish: return "🇹🇷"
        }
    }
}

/// The reason a pick was chosen, as `why_fact.reason` names it.
public enum PickReason: String {
    case highestScore = "highest_score"
    case cheapestWithinWindow = "cheapest_within_window"
    case cheapestAboveFloor = "cheapest_above_floor"
    case nothingClearsFloor = "nothing_clears_floor"
    /// D-159 (M17-W1): the surface's own board is empty, so there is no floor to clear.
    case noFloorMeasured = "no_floor_measured"
}

/// Compose the "why" sentence from the engine's fact.
///
/// Returns `nil` when the fact carries a reason this build does not know — a newer engine, an
/// older app. The caller falls back to the engine's own English prose, which is always present
/// (D-136 is additive). **Showing the English is not a failure; inventing a Turkish sentence for a
/// reason we do not understand would be.**
public func whySentence(_ fact: [String: Any], in language: Language) -> String? {
    guard let raw = fact["reason"] as? String, let reason = PickReason(rawValue: raw) else {
        return nil
    }
    // **Every value the sentence quotes is resolved BEFORE a word is written.** The guard is the
    // sentence's precondition, not a decoration on one branch: `?? ""` on a missing benchmark used
    // to ship `The highest score on  among the models you can afford.` — a sentence naming no
    // benchmark while claiming a model tops it.
    guard let unit = label(fact["unit"]).map({ localisedUnit($0, in: language) }) else { return nil }
    switch (reason, language) {
    case (.highestScore, .english):
        guard let benchmark = label(fact["benchmark"]) else { return nil }
        // M13-W3 review MINOR-1: not "among the models you can afford". With the budget control
        // gone the reader has set no budget, and a sentence saying they did describes a choice
        // they never made.
        return "The highest score on \(benchmark) of all the models ranked here."
    case (.highestScore, .turkish):
        guard let benchmark = label(fact["benchmark"]) else { return nil }
        // Not "Burada sıralanan": `HostileFactValueTests` hunts the ghost `nan` in every sentence,
        // and "sıralanan" carries it. The test is right to be blunt; the sentence moved.
        return "Buradaki tüm modeller arasında \(benchmark) üzerindeki en yüksek puan."
    case (.cheapestWithinWindow, .english):
        guard let window = number(fact["window"]) else { return nil }
        return "The cheapest model that is still within \(window) \(unit) of the best one."
    case (.cheapestWithinWindow, .turkish):
        guard let window = number(fact["window"]) else { return nil }
        return "En iyisinin \(window) \(unit) yakınında kalan en ucuz model."
    case (.cheapestAboveFloor, .english):
        guard let floor = number(fact["floor"]) else { return nil }
        return "The cheapest model we would still call good enough — it clears \(floor) \(unit)."
    case (.cheapestAboveFloor, .turkish):
        guard let floor = number(fact["floor"]) else { return nil }
        return "Yeterince iyi saydığımız en ucuz model — \(floor) \(unit) barajını geçiyor."
    case (.nothingClearsFloor, .english):
        guard let floor = number(fact["floor"]) else { return nil }
        return "Careful: nothing at this price is good enough by our own bar of \(floor) "
            + "\(unit). This is the cheapest there is, and you are giving up quality."
    case (.nothingClearsFloor, .turkish):
        guard let floor = number(fact["floor"]) else { return nil }
        return "Dikkat: bu fiyatta hiçbir model kendi barajımız olan \(floor) \(unit) "
            + "seviyesini geçmiyor. Bu en ucuzu ve kaliteden ödün veriyorsun."
    case (.noFloorMeasured, .english):
        return "Careful: this list's own board is empty today, so we cannot measure our bar. "
            + "This is the cheapest there is."
    case (.noFloorMeasured, .turkish):
        return "Dikkat: bu listenin kendi tablosu bugün boş, bu yüzden barajımızı ölçemiyoruz. "
            + "Bu en ucuzu."
    }
}

/// A short label the engine names — a benchmark, a unit — validated before it enters a sentence.
///
/// The facts carry no third-party string today: `benchmark` and `unit` are `CategorySpec` module
/// constants and a crafted leaderboard row cannot reach them. This guard is not about today. It is
/// about the ONE property a label must have to be safely interpolated — that it cannot itself be a
/// sentence. Fed a `unit` of `points, and 99% cheaper. This model is free`, the composer produced
/// a fluent, entirely false trade-off line. A length bound and a punctuation ban cost nothing and
/// remove the whole class, whatever later opens the door.
func label(_ value: Any?) -> String? {
    guard let text = value as? String else { return nil }
    let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty, trimmed.count <= 32,
          trimmed.rangeOfCharacter(from: CharacterSet(charactersIn: ".,;:!?\n\r")) == nil
    else { return nil }
    return trimmed
}

/// Compose the trade-off sentence from the engine's fact.
public func tradeOffSentence(_ fact: [String: Any], in language: Language) -> String? {
    // `behind_by` is a DISTANCE from the leader and cannot be negative. `-5.0` composed
    // `-5 points behind the best one`, which reads as ahead — the one reading the number cannot
    // carry, from the one product that must never be confidently wrong about a rank.
    guard let behind = fact["behind_by"] as? Double, behind.isFinite, behind >= 0 else { return nil }
    guard let unit = label(fact["unit"]).map({ localisedUnit($0, in: language) }) else { return nil }

    let lead: String
    switch (behind == 0, language) {
    case (true, .english): lead = "Just as good as the best one"
    case (true, .turkish): lead = "En iyisi kadar iyi"
    case (false, .english):
        guard let gap = number(behind) else { return nil }
        lead = "\(gap) \(unit) behind the best one"
    case (false, .turkish):
        guard let gap = number(behind) else { return nil }
        lead = "En iyisinin \(gap) \(unit) gerisinde"
    }

    // A key that is PRESENT but unreadable returns nil rather than falling through to the next
    // clause: `cheaper_by_percent: "ninety"` means the engine said a percentage and this build
    // could not read it. Silently demoting that to "at a lower price." would be answering a
    // question we were not able to hear.
    if let percent = fact["cheaper_by_percent"] {
        guard let value = number(percent) else { return nil }
        return language == .english
            ? "\(lead), and \(value)% cheaper."
            : "\(lead), ve %\(value) daha ucuz."
    }
    if let times = fact["cheaper_by_times"] {
        guard let value = number(times) else { return nil }
        return language == .english
            ? "\(lead), but \(value)× cheaper."
            : "\(lead), ama \(value) kat daha ucuz."
    }
    if (fact["cheaper"] as? String) == "same" {
        return language == .english ? "\(lead), at the same price." : "\(lead), aynı fiyata."
    }
    return language == .english ? "\(lead), at a lower price." : "\(lead), daha ucuza."
}

/// The score's unit, in the sentence's language.
///
/// **Seen on the first Turkish screenshot: "En iyisinin 6 points yakınında".** The unit arrives
/// from the engine as a display label — `points`, `% resolved` — and interpolating it raw put an
/// English word inside a Turkish sentence. A half-translated sentence reads worse than an
/// untranslated one, because the reader cannot tell which half to trust.
///
/// `elo` and `ECI` stay as they are in both languages: they are the names of scales, not words,
/// and translating a proper noun would make two readers unable to compare notes. That is the same
/// reasoning as leaving the digits alone.
public func localisedUnit(_ unit: String, in language: Language) -> String {
    guard language == .turkish else { return unit }
    switch unit {
    case "points": return "puan"
    case "% resolved": return "% çözülen"
    case "% correct": return "% doğru"
    default: return unit
    }
}

/// What a score's scale IS, in the sentence's language. The English lives in `scaleExplanation`.
public func scaleExplanation(for metric: String, in language: Language) -> String? {
    guard language == .turkish else { return scaleExplanation(for: metric) }
    switch metric.lowercased() {
    case "elo":
        return "insanların cevapları yan yana kıyaslamasından çıkan bir puan"
    case "eci":
        return "genel yetenek endeksi — sabit bir üst sınırı yok"
    // #63 finding 8: "gerçek işlerin ne kadarını bitirdiği" had no subject and read as a fragment.
    case "% resolved":
        return "modelin çözdüğü gerçek görevlerin yüzdesi"
    case "% correct":
        return "modelin doğru yanıtladığı soruların yüzdesi"
    default:
        return nil
    }
}

/// What the card's score means once D-143 has put it out of 100. `nil` where the scale is not an
/// anchored Elo, so the caller keeps the metric's own explanation.
public func anchoredScaleExplanation(for metric: String, anchored: Bool, in language: Language)
    -> String?
{
    guard anchored, metric.lowercased() == "elo" else { return nil }
    switch language {
    case .english:
        return "out of 100: how often people prefer it over a model at the bar we recommend from — "
            + "50 is at the bar"
    case .turkish:
        // #63 finding 8: the first wording was hard to follow. Same facts, said plainly.
        return "100 üzerinden: insanlar iki cevabı yan yana görünce bu modelinkini ne sıklıkla seçiyor. "
            + "50, önerdiğimiz alt sınırdaki bir modelle eşit demek"
    }
}

/// The price in pages, in the sentence's language.
public func priceInPages(_ blendedPerM: Double, in language: Language) -> String {
    guard language == .turkish else { return priceInPages(blendedPerM) }
    guard blendedPerM.isFinite, blendedPerM > 0 else { return "fiyat bilinmiyor" }
    let perPage = blendedPerM / Double(pagesPerMillionTokens)
    if perPage < 0.01 {
        guard let amount = money(blendedPerM) else {
            return "\(groupedPages(.turkish)) sayfa metin için $0.01'den az"
        }
        return "\(groupedPages(.turkish)) sayfa metin için yaklaşık $\(amount)"
    }
    return "sayfa başına yaklaşık $\(String(format: "%.2f", perPage))"
}

/// Print a number from a fact without trailing-zero noise, and without the reader's locale.
///
/// Pinned to POSIX for the same reason the model filter is: these are values the ENGINE decided,
/// and a number that changes shape between devices reads as a different answer. The Turkish decimal
/// comma is a real convention and it is deliberately not applied here — `4.4 puan` is the engine's
/// number, and rendering it as `4,4` in one language and `4.4` in the other would make two readers
/// unable to compare notes.
/// Returns `nil` for anything this build cannot render as a number — and `nil` is the whole point.
///
/// **This returned `""` until M12-W5, and the composers interpolated it into the sentence anyway.**
/// Measured by the Stage 4.0 seat: a `cheaper_by_percent` of `"ninety"` shipped
/// `2.7 points behind the best one, and % cheaper.` — the claim intact, the magnitude deleted.
/// A sentence that has lost its number has not degraded gracefully; it has started lying, because
/// the reader supplies the missing quantity themselves and has no way to know they did.
///
/// Non-finite is the same case. `nan` is a `Double` and formats happily as the word `nan`, which
/// reads as a number to nobody and as a typo to everybody.
func number(_ value: Any?) -> String? {
    switch value {
    case let double as Double:
        guard inRange(double) else { return nil }
        return wholeNumber(double) ?? String(format: "%.1f", double)
    case let int as Int:
        return inRange(Double(int)) ? String(int) : nil
    default:
        return nil
    }
}

/// **Every number that reaches a sentence in this app is a non-negative, bounded quantity** — a
/// score, a points gap, a percentage, a price multiple. None of them can be negative and none can
/// be astronomical, so a value that is either did not come from a working engine.
///
/// `isFinite` alone is not enough, and the test caught it the same hour it was written: `-1e19` is
/// perfectly finite and composed *"it clears -10000000000000000000.0 points"*. A finite check asks
/// whether the machine can represent the number; this asks whether the PRODUCT can mean it.
private func inRange(_ value: Double) -> Bool {
    value.isFinite && value >= 0 && value <= 1_000_000
}

/// `Int(Double)` TRAPS. It is not a conversion, it is an assertion that the value fits — and the
/// values here come off the wire.
///
/// Measured by the M12 Stage 4.0 seat against unmodified sources: a well-formed `/v1` answer
/// carrying `"floor": 1e19` or a negative price kills the process with `SIGTRAP`, and the client's
/// own contract — an unreadable payload becomes `undecodable` and the screen says so — promises
/// exactly the opposite. **A trap bypasses every failure path this app has.**
///
/// `nil` when the value cannot be a whole number, which is not an error: the caller falls back to
/// a decimal rendering, and a number the reader cannot use is still better than an app that is
/// gone.
func wholeNumber(_ value: Double) -> String? {
    guard value.isFinite, value == value.rounded(),
          value >= -9_007_199_254_740_992, value <= 9_007_199_254_740_992
    else { return nil }
    return String(Int(value))
}

// MARK: - The screen's own words
//
// Everything above composes a sentence from an engine FACT. Everything here is the app's own
// chrome, which no fact governs — a title, a placeholder, a button. It is a string table and it
// says so: a table is the right shape for text that carries no values, and the wrong shape for a
// sentence that quotes numbers, which is the distinction D-136 turns on.

public enum UIText {
    /// The metric as it appears beside a score — `83.5 % resolved`.
    ///
    /// The same map as `localisedUnit`, reached from the view rather than from a fact. It is here
    /// and not there because a fact's `unit` and an answer's `metric` are the same vocabulary
    /// arriving by two routes, and giving them two translations would be how they drift.
    public static func metric(_ metric: String, _ language: Language) -> String {
        localisedUnit(metric, in: language)
    }

    public static func title(_ language: Language) -> String {
        language == .turkish ? "Hangi model?" : "Which model?"
    }

    public static func askPlaceholder(_ language: Language) -> String {
        language == .turkish ? "Yapay zekânın ne yapmasını istiyorsun?" : "What do you want an AI to do?"
    }

    public static func filterPlaceholder(_ language: Language) -> String {
        language == .turkish ? "Model adına göre süz" : "Filter by model name"
    }

    public static func seeAll(_ total: Int, eligible: Int?, _ language: Language) -> String {
        guard let eligible, eligible < total else {
            return language == .turkish ? "\(total) modelin tamamı" : "See all \(total)"
        }
        return language == .turkish
            ? "\(total) modelin tamamı — \(eligible) tanesi bütçene uyuyor"
            : "See all \(total) — \(eligible) fit your budget"
    }

    /// The engine's pick labels — `best_quality`, `best_value`, `budget_pick` — as words.
    ///
    /// Read from the LABEL rather than the position, because the three picks answer three
    /// different questions and the label is the only thing that says which.
    public static func pickLabel(_ label: String, _ language: Language) -> String {
        switch (label, language) {
        case ("best_quality", .turkish): return "EN İYİSİ"
        case ("best_value", .turkish): return "EN İYİ DEĞER"
        // M13-W4: not "BUDGET PICK". With no budget control on the screen, a label saying the
        // reader set a budget is false; the pick is the cheapest model that clears the floor
        // (plan §2 W4). The engine's id `budget_pick` is the contract (D-127) and does not move.
        case ("budget_pick", .english): return "AFFORDABLE PICK"
        case ("budget_pick", .turkish): return "UYGUN FİYATLI SEÇİM"
        default: return label.replacingOccurrences(of: "_", with: " ").uppercased()
        }
    }

    /// The control that corrects the surface the router chose (M13-W3, REQ-ASK-002).
    public static func change(_ language: Language) -> String {
        language == .turkish ? "Değiştir" : "Change"
    }

    /// Before any question has been asked: which surface is on screen.
    public static func showing(_ language: Language) -> String {
        language == .turkish ? "Gösterilen" : "Showing"
    }

    /// The send button's accessibility label. The button itself is an arrow.
    public static func send(_ language: Language) -> String {
        language == .turkish ? "Sor" : "Ask"
    }

    /// The gap register's title (M14-W3): what people asked that we cannot yet answer.
    public static func gapsTitle(_ language: Language) -> String {
        language == .turkish ? "Sorulan ama ölçmediklerimiz" : "Asked, but not measured"
    }

    /// The register when nothing has been recorded yet.
    public static func noGaps(_ language: Language) -> String {
        language == .turkish
            ? "Henüz ölçmediğimiz bir soru sorulmadı."
            : "Nobody has asked anything we do not measure yet."
    }

    /// Empties the register on this device.
    public static func clearGaps(_ language: Language) -> String {
        language == .turkish ? "Temizle" : "Clear"
    }

    // MARK: - The screen's chrome (M15 UI refresh)
    //
    // **These eleven were written for the 2026-09-22 refresh and then DELETED by accident**, when
    // the M15-W3 wave wrote this file from a copy that predated them; `ContentView.swift` went on
    // calling all eleven and only the Xcode build could see it (`swift test` does not compile the
    // view). The originals were never committed, so these are replacements rather than a restore:
    // the same jobs, in this file's voice, and the wording is open to the owner's correction.
    // `test_ios_client_contract.py::test_every_screen_string_the_client_calls_exists` is the guard
    // that makes the next deletion fail a gate instead of a build.

    /// The progress label while the first answer is being fetched.
    public static func loading(_ language: Language) -> String {
        language == .turkish ? "Yükleniyor…" : "Loading…"
    }

    /// The opening line of the home screen, above the question field.
    public static func heroTitle(_ language: Language) -> String {
        language == .turkish ? "Hangi modeli kullanmalısın?" : "Which model should you use?"
    }

    /// One line under it, saying what this product is and is not.
    public static func heroSubtitle(_ language: Language) -> String {
        language == .turkish
            ? "Kendi cümlelerinle sor. Buradaki her sayı herkese açık bir ölçümden geliyor."
            : "Ask in your own words. Every number here comes from a public measurement."
    }

    /// The small label above the question field.
    public static func questionEyebrow(_ language: Language) -> String {
        language == .turkish ? "SORU" : "YOUR QUESTION"
    }

    /// Beside the lock icon: D-126, said to the reader rather than only to the repository.
    /// Worded as what THIS APP does (M15 closure security seat, MINOR-2): "stays on this device"
    /// promised more than the app controls, since a third-party keyboard with Full Access or system
    /// dictation sees the text before the app does.
    public static func privateQuestion(_ language: Language) -> String {
        language == .turkish
            ? "Bu uygulama yazdıklarını hiçbir yere göndermez."
            : "This app never sends what you type anywhere."
    }

    /// A surface that ranked nothing. The engine's own reason is shown under it.
    public static func noPicks(_ language: Language) -> String {
        language == .turkish ? "Burada önerebileceğimiz model yok" : "Nothing to recommend here"
    }

    /// The engine could not be reached, or refused. The error's own sentence follows.
    public static func noAnswer(_ language: Language) -> String {
        language == .turkish ? "Şu anda cevap yok" : "No answer right now"
    }

    /// The engine address the app asked, under a failure to reach it (M18-W1 review B2).
    public static func engineAddress(_ language: Language, _ address: String) -> String {
        language == .turkish ? "Motor adresi: \(address)" : "Engine address: \(address)"
    }

    public static func retry(_ language: Language) -> String {
        language == .turkish ? "Tekrar dene" : "Try again"
    }

    /// The model filter matched nothing, and what to try instead.
    public static func noMatches(_ language: Language) -> String {
        language == .turkish ? "Eşleşen model yok" : "No model matches"
    }

    public static func noMatchesHint(_ language: Language) -> String {
        language == .turkish
            ? "Model ya da sağlayıcı adının bir kısmını yazmayı dene."
            : "Try part of a model or a vendor name."
    }

    /// The tap target on a card, worded as what the reader gets rather than as "Details".
    public static func openEvidence(_ language: Language) -> String {
        language == .turkish ? "Kanıta bak" : "See the evidence"
    }

    /// The detail screen's title and its one caveat (M15-W2, REQ-DTL-001/002).
    public static func detailTitle(_ language: Language) -> String {
        language == .turkish ? "Bu sayı nereden geliyor" : "Where this number comes from"
    }

    /// Said once, at the bottom, because a reader who opened this screen is comparing something.
    public static func detailCaveat(_ language: Language) -> String {
        language == .turkish
            ? "Her alan kendi listesinden ölçülür. İki alanın puanı birbiriyle kıyaslanamaz."
            : "Each surface is measured on its own board. Two surfaces' scores do not compare."
    }

    /// The Change sheet's title.
    public static func chooseSurface(_ language: Language) -> String {
        language == .turkish ? "Neyi sıralayalım?" : "What should we rank?"
    }

    /// Before the one-tap alternatives under the echo.
    public static func alternatives(_ language: Language) -> String {
        language == .turkish ? "Ya da:" : "Or:"
    }

    /// Before the surfaces offered under a DECLINED question (W3 re-review-2 R3-1). They are not
    /// alternatives to a match, because nothing matched; they are the nearest things this catalogue
    /// does measure, and "Or:" above `Puzzles` for a cat picture read as a suggestion.
    public static func closestMeasured(_ language: Language) -> String {
        language == .turkish ? "Ölçtüklerimizden en yakınları:" : "Closest we measure:"
    }

    /// When the engine's list of surfaces could not be read (M13-W3 review MINOR-7). A question
    /// cannot be routed without it and the Change sheet would be empty, so the card says so rather
    /// than offering a send button that silently does nothing.
    public static func surfacesUnavailable(_ language: Language) -> String {
        language == .turkish
            ? "Alan listesi yüklenemedi; yeniden denemek için aşağı çek."
            : "The list of surfaces could not be loaded; pull down to try again."
    }

    /// What a surface is for, in one line under its name in the chooser (#63 finding 13, M18-W2):
    /// three names blurred together with nothing between them. Keyed on the engine's id, like
    /// `surface`; `nil` for an id this build does not know, which then shows its name alone.
    public static func surfaceBlurb(_ id: String, _ language: Language) -> String? {
        let lines: [String: (String, String)] = [
            "coding": ("Fixing real bugs in real code", "Gerçek koddaki gerçek hataları düzeltmek"),
            "agentic-coding": ("An agent that plans and edits many files on its own",
                               "Planlayıp birçok dosyayı kendi başına düzenleyen bir ajan"),
            "assistant": ("Everyday chat: emails, advice, explanations", "Gündelik sohbet: e-posta, tavsiye, açıklama"),
            "everyday": ("Useful across many ordinary tasks at once", "Birçok sıradan işte birden faydalı olmak"),
            "expert": ("Graduate-level science questions", "Lisansüstü düzeyde fen soruları"),
            "mathematics": ("Maths problems, proofs, competition questions",
                            "Matematik problemleri, ispatlar, yarışma soruları"),
            "computer-use": ("Operating a computer: clicking, typing, using apps",
                             "Bilgisayarı kullanmak: tıklamak, yazmak, uygulama kullanmak"),
            "abstract": ("Puzzles and patterns it has never seen", "Daha önce görmediği bulmacalar ve örüntüler"),
            "web-dev": ("Building websites and web apps", "Web siteleri ve web uygulamaları yapmak"),
            "document": ("Reading and working with long documents", "Uzun belgeleri okumak ve onlarla çalışmak"),
            "factuality": ("Getting facts right in its own answers", "Kendi cevaplarında bilgiyi doğru vermek"),
            "vision": ("Reading images and screenshots", "Görselleri ve ekran görüntülerini okumak"),
            "search": ("How well it answers by searching the web", "İnternette arayarak ne kadar iyi cevap verdiği"),
            "search_factuality": ("Reporting what a search found without making things up",
                                  "Aramada bulduğunu uydurmadan aktarmak"),
        ]
        guard let line = lines[id] else { return nil }
        return language == .turkish ? line.1 : line.0
    }

    /// What the gap register is for (#63 finding 14), at the top of its sheet.
    public static func gapsPurpose(_ language: Language) -> String {
        language == .turkish
            ? "Ölçmediğimiz bir şey sorduğunda soru burada, yalnızca bu cihazda tutulur. Neyin ölçülmesi "
                + "gerektiğini gösterir."
            : "When you ask about something we do not measure, the question is kept here, on this device "
                + "only. It shows what is worth measuring next."
    }

    /// The visible label beside the register's icon (#63 finding 14).
    public static func gapsButton(_ language: Language) -> String {
        language == .turkish ? "Ölçülmeyenler" : "Not measured"
    }

    /// A surface's name.
    ///
    /// Keyed on the engine's ID, never on its English title: the id is the contract (D-127) and
    /// the title is the product. Keying on the title would break the Turkish screen every time
    /// somebody improved an English name — which happened six times at M12-W2 alone.
    ///
    /// An unknown id falls back to whatever the engine called it. A surface this build has not
    /// heard of still appears, in English, rather than vanishing: hiding a surface the engine
    /// serves would be a worse answer than showing it in the wrong language.
    public static func surface(id: String, engineTitle: String, _ language: Language) -> String {
        guard language == .turkish else { return engineTitle }
        switch id {
        case "coding": return "Kod yazma"
        case "agentic-coding": return "Kendi başına kod yazma"
        case "assistant": return "Sohbet"
        case "everyday": return "Genel bilgi"
        case "expert": return "Zor fen soruları"
        case "mathematics": return "Matematik"
        case "computer-use": return "Bilgisayar kullanma"
        case "abstract": return "Bulmaca ve örüntü"
        case "web-dev": return "Web geliştirme"
        case "document": return "Belgelerle çalışma"
        case "factuality": return "Doğru bilgi verme"
        case "vision": return "Görsel ve ekran görüntüsü okuma"
        case "search": return "İnternetten arayıp cevaplama"
        case "search_factuality": return "Aradığını doğru aktarma"
        default: return engineTitle
        }
    }
}


// MARK: - M17-W5 (D-168): refinements and the combined list

extension UIText {
    /// Each refinement's name, keyed by its table value: (English, Turkish). A test holds every
    /// table entry to a name in both languages.
    static let refinementNames: [String: (String, String)] = [
        "chinese": ("Chinese", "Çince"),
        "french": ("French", "Fransızca"),
        "german": ("German", "Almanca"),
        "japanese": ("Japanese", "Japonca"),
        "korean": ("Korean", "Korece"),
        "polish": ("Polish", "Lehçe"),
        "russian": ("Russian", "Rusça"),
        "spanish": ("Spanish", "İspanyolca"),
        "legal": ("Law and government", "Hukuk ve kamu"),
        "medicine": ("Medicine and health", "Tıp ve sağlık"),
        "business": ("Business and finance", "İş ve finans"),
        "software": ("Software and IT", "Yazılım ve BT"),
        "writing": ("Writing and language", "Yazı ve dil"),
        "entertainment": ("Entertainment and media", "Eğlence ve medya"),
        "science": ("Science", "Bilim"),
        "mathematical": ("Mathematics as a field", "Matematik alanı"),
    ]

    static func refinementName(_ refinement: Refinement, _ language: Language) -> String {
        guard let names = refinementNames[refinement.value] else { return refinement.value }
        return language == .turkish ? names.1 : names.0
    }

    /// #208: under the question, very small: which tier reads it.
    static func onDeviceCaption(_ available: Bool, _ language: Language) -> String {
        switch (available, language) {
        case (true, .turkish): return "Apple Intelligence ile güçlendirildi"
        case (true, _): return "Apple Intelligence enhanced"
        case (false, .turkish): return "Apple Intelligence kapalı: sorular kelimelerle eşleşiyor"
        case (false, _): return "Apple Intelligence off: questions are matched by their words"
        }
    }

    /// D-188 clause 5 (M20-W4): the primary board's own answer, and back to the combined list.
    static func primaryOnItsOwn(_ language: Language) -> String {
        language == .turkish ? "Yalnızca ana tablonun cevabını göster" : "Show the primary board's own answer"
    }

    static func backToCombined(_ language: Language) -> String {
        language == .turkish ? "Birleşik listemize dön" : "Back to our combined list"
    }

    static func combinedTitle(_ language: Language) -> String {
        language == .turkish ? "Bu soruya göre birleşik sıralama" : "Combined for this question"
    }

    /// D-160 clause 3: the list is the product's own, and says so.
    static func combinedNote(models: Int, boards: Int, _ language: Language) -> String {
        language == .turkish
            ? "Uygulamanın kendi listesi: \(boards) panonun hepsinde yer alan \(models) model, her panodaki "
                + "sıralarına göre dizildi. Bu sırayı hiçbir liste yayımlamıyor."
            : "The app's own list: \(models) models ranked on all \(boards) boards, ordered by their places "
                + "on each. No leaderboard publishes this order."
    }

    static func combinedEmpty(_ language: Language) -> String {
        language == .turkish
            ? "Bu panoların hepsinde yer alan bir model yok. Liste için yukarıdan bir panoyu çıkar."
            : "No model is ranked on every one of these boards. Remove a board above to see a list."
    }

    static func alsoCounting(_ language: Language) -> String {
        language == .turkish ? "Şunlar da hesaba katıldı" : "Also counted"
    }

    /// Above the cards when the reader removed every refinement (D-168 clause 7).
    static func removedRefinements(_ language: Language) -> String {
        language == .turkish ? "Çıkardıkların; geri eklemek için dokun" : "Removed; tap one to count it again"
    }

    /// D-112 on the combined list (review B1): the cards' `effort_mix_notice`, said of the list.
    static func combinedEffortNote(efforts: [String], _ language: Language) -> String {
        let named = efforts.map { effortName($0, language) }.joined(separator: ", ")
        return language == .turkish
            ? "Not: Bu panolar modelleri tek bir çaba düzeyinde karşılaştırmıyor ve bu listedeki modeller "
                + "farklı düzeylerde ölçüldü (\(named)). Daha yüksek çabayla çalıştırılan bir model, daha düşük "
                + "çabayla çalıştırılandan iyi görünebilir."
            : "Note: these boards do not compare at one effort level, and the models in this list were "
                + "measured at different levels (\(named)). A model run at a higher effort can look better "
                + "than one run at a lower effort."
    }

    /// The efforts the listed models stand at on one board, in the detail.
    static func boardEfforts(_ efforts: [String], _ language: Language) -> String {
        let named = efforts.map { effortName($0, language) }.joined(separator: ", ")
        return language == .turkish ? "Bu listedeki modellerin çaba düzeyleri: \(named)"
            : "Effort levels of the models in this list: \(named)"
    }

    /// A board's date, saying whether anything was measured on it (review B1).
    static func boardDate(_ date: BoardDate, _ language: Language) -> String {
        switch date {
        case let .measured(served):
            let day = readableDate(served, language) ?? served
            return language == .turkish ? "En yeni ölçüm: \(day)" : "Newest evaluation: \(day)"
        case let .readOn(served):
            let day = readableDate(served, language) ?? served
            return language == .turkish
                ? "Ölçüm tarihi yayımlamıyor; motor \(day) tarihinde okudu"
                : "Publishes no evaluation date; read by the engine on \(day)"
        case .unknown:
            return language == .turkish ? "Tarih yok" : "No date"
        }
    }

    /// What a tap on a refinement's chip does, for VoiceOver (review M4).
    static func chipAction(_ refinement: Refinement, removed: Bool, _ language: Language) -> String {
        let name = refinementName(refinement, language)
        switch (language, removed) {
        case (.turkish, false): return "\(name) panosunu çıkar"
        case (.turkish, true): return "\(name) panosunu geri ekle"
        case (_, false): return "Remove the \(name) board"
        case (_, true): return "Add the \(name) board back"
        }
    }

    /// D-188 clause 4 (M20-W4): the family's boards that weigh half, said small, under the list.
    static func boardsWeighHalf(_ benchmarks: [String], _ language: Language) -> String {
        let names = benchmarks.joined(separator: ", ")
        return language == .turkish
            ? "\(names) bu listede yarım ağırlıkta: 90 gündür yeni sonuç eklenmedi ya da tarih yok."
            : "\(names) weighs half in this list: no new result in 90 days, or no date."
    }

    /// Under a combined list with tied places (1, 1, 3): what a shared place means.
    static func tiedPlaces(_ language: Language) -> String {
        language == .turkish
            ? "Aynı sırayı paylaşan modeller berabere: panolardaki yerleri birbirini dengeliyor."
            : "Models sharing a place are tied: their places on the boards balance out."
    }

    /// D-169 (M18-W3): the note for input that is not a model search, in the owner's wording
    /// (2026-09-28): example-based guidance, in the app's register.
    static func notASearchNote(_ language: Language) -> String {
        language == .turkish
            ? "Bu bir model araması gibi görünmüyor. Modeli ne için kullanacağını yaz; örneğin: "
                + "\"Bir e-postayı Fransızcaya çevirmek istiyorum.\""
            : "This does not look like a model search. Say what you will use the model for; for example: "
                + "\"I want to translate an email into French.\""
    }

    /// D-169 (M18-W3): the question back, when one sign says it is not a search and the other does not.
    static func askBack(_ language: Language) -> String {
        language == .turkish ? "Bunun için bir model mi arıyorsun?" : "Did you mean to find a model for this?"
    }

    static func askBackFind(_ language: Language) -> String {
        language == .turkish ? "Model bul" : "Find a model"
    }

    static func askBackNo(_ language: Language) -> String {
        language == .turkish ? "Hayır" : "No"
    }

    /// #78: the combined list's reader filter, and how many rows it leaves.
    static func accessFilter(_ language: Language) -> String {
        language == .turkish ? "Yalnızca API'si ya da açık ağırlıkları olan modeller"
            : "Only models with an API or open weights"
    }

    static func accessFilterCount(shown: Int, of total: Int, _ language: Language) -> String {
        language == .turkish
            ? "\(total) modelin \(shown) tanesi gösteriliyor; sıralar \(total) modelin tamamı içinde"
            : "\(shown) of \(total) shown; places are among all \(total)"
    }

    /// Review M3 (#72): the combined list's standings are an old copy kept on this phone.
    static func stalePhoneCopy(days: Int, _ language: Language) -> String {
        language == .turkish
            ? "Bu listenin dayandığı sıralamalar bu telefona \(days) gün önce indirildi; daha yenisi alınamadı."
            : "The standings behind this list reached this phone \(days) days ago; a newer copy could not be fetched."
    }

    /// The control under a shortened combined list.
    static func showAll(_ total: Int, _ language: Language) -> String {
        language == .turkish ? "\(total) modelin hepsini göster" : "Show all \(total)"
    }

    static func showFewer(_ language: Language) -> String {
        language == .turkish ? "Daha az göster" : "Show fewer"
    }

    static func seeTheBoards(_ language: Language) -> String {
        language == .turkish ? "Panolara bak" : "See the boards"
    }

    static func boardsBehind(_ language: Language) -> String {
        language == .turkish ? "Bu listenin dayandığı panolar" : "The boards behind this list"
    }

    static func placeOn(_ benchmark: String, place: Int, _ language: Language) -> String {
        language == .turkish ? "\(benchmark) listesinde #\(place)" : "#\(place) on \(benchmark)"
    }
}

// MARK: - M18-W2 (#96): the failure screen's sentences

extension EngineError {
    /// What happened, in the reader's language. English is `errorDescription` itself, so the two
    /// cannot drift; the engine's own refusal is shown as it sent it, in either language.
    func errorDescription(_ language: Language) -> String? {
        guard language == .turkish else { return errorDescription }
        switch self {
        case .unreachable: return "Motor yanıt vermiyor."
        case let .timedOut(seconds): return "Motor \(seconds) saniye içinde yanıt vermedi."
        case .insecureTransport: return "Bağlantı şifreli olmadığı için reddedildi."
        case .offline: return "Bu cihazın ağ bağlantısı yok."
        case let .refused(_, _, message): return message
        case .undecodable: return "Motorun cevabı bu uygulamanın okuyabildiği biçimde değildi."
        }
    }

    /// What the person holding the phone can do, in their language. `nil` exactly where `recovery` is.
    func recovery(_ language: Language) -> String? {
        guard language == .turkish else { return recovery }
        switch self {
        case .unreachable:
            return "Bu soruları cevaplayan servise şu anda ulaşılamıyor. Biraz sonra tekrar dene."
        case .timedOut:
            return "Çok yavaş cevap verdi. Tekrar denemek genellikle işe yarar."
        case .insecureTransport:
            return "Bu bağlantı şifreli olmadığı için reddedildi. Bu, telefonun seni koruması; buradan "
                + "düzeltebileceğin bir hata değil."
        case .offline:
            return "Bu cihazın internet bağlantısı yok. Yeniden bağlan ve tekrar dene."
        case .refused:
            return nil
        case .undecodable:
            return "Uygulamanın bu sürümü gönderilen cevabı okuyamadı. Çözüm, uygulamayı güncellemek."
        }
    }
}

/// An effort level as the reader's language names it (M18-W2 review K2). English keeps the engine's
/// word; a level this build does not know keeps its name in both.
func effortName(_ effort: String, _ language: Language) -> String {
    guard language == .turkish else { return effort }
    switch effort {
    case "minimal": return "en düşük"
    case "low": return "düşük"
    case "medium": return "orta"
    case "high": return "yüksek"
    case "xhigh": return "çok yüksek"
    case "max": return "en yüksek"
    case "unspecified": return "belirtilmemiş"
    default: return effort
    }
}
