//  ModelFamilies.swift -- the family words of the models the engine ranks (#194, M21-W2).
//
//  GENERATED by `scripts/model_family_words.py` from `app.workflows.registry`; do not edit by hand.
//  `tests/unit/test_model_families.py` holds this file equal to the registry.

enum ModelFamilies {
    /// Every family word the registry names a ranked model by, in plain lower case.
    static let words: Set<String> = [
        "aya", "claude", "code", "codestral", "command", "dbrx", "deepseek", "devstral", "doubao", "ernie",
        "gemini", "gemma", "glm", "gpt", "granite", "grok", "jamba", "kimi", "llama", "magistral", "mercury",
        "mimo", "minimax", "ministral", "mistral", "mixtral", "nemotron", "nous", "nova", "nvidia", "o1",
        "o3", "o4", "palmyra", "phi", "pixtral", "qwen", "qwq", "step", "titan", "trinity", "zephyr",
    ]
    /// The family words that are also plain English or Turkish; they name a model only beside a version.
    /// The tokens the registry's names put after an ambiguous family word (a stub in the red commit).
    static let versions: [String: Set<String>] = [:]
    static let ambiguous: Set<String> = [
        "aya", "code", "command", "ernie", "granite", "jamba", "kimi", "llama", "mercury", "nous", "nova",
        "palmyra", "phi", "step", "titan", "trinity", "zephyr",
    ]
}
