"""Write `ios/ModelRanking/Engine/ModelFamilies.swift` from the engine's registry (#194, M21-W2).

The phone reads a search that names a model the engine ranks as a search, never a question of fact.
The names come from the registry, not a hand-kept list; `tests/unit/test_model_families.py` holds the
written file equal to it. Run after a change to the registry's families or display names:

    .venv/bin/python scripts/model_family_words.py
"""

from __future__ import annotations

import pathlib

from app.workflows.registry import AMBIGUOUS_FAMILY_WORDS, family_versions, family_words

SWIFT = pathlib.Path(__file__).resolve().parents[1] / "ios/ModelRanking/Engine/ModelFamilies.swift"


def _set(words: frozenset[str]) -> str:
    items = sorted(words)
    lines, line = [], "       "
    for item in items:
        piece = f' "{item}",'
        if len(line) + len(piece) > 110:
            lines.append(line)
            line = "       "
        line += piece
    lines.append(line)
    return "[\n" + "\n".join(lines) + "\n    ]"


def _versions() -> str:
    lines = [f'        "{word}": [{", ".join(chr(34) + v + chr(34) for v in sorted(after))}],'
             for word, after in sorted(family_versions().items())]
    return "[\n" + "\n".join(lines) + "\n    ]"


def render() -> str:
    """The Swift file, as this registry would write it."""
    return f"""//  ModelFamilies.swift -- the family words of the models the engine ranks (#194, M21-W2).
//
//  GENERATED by `scripts/model_family_words.py` from `app.workflows.registry`; do not edit by hand.
//  `tests/unit/test_model_families.py` holds this file equal to the registry.

enum ModelFamilies {{
    /// Every family word the registry names a ranked model by, in plain lower case.
    static let words: Set<String> = {_set(family_words())}
    /// The family words that are also plain English or Turkish; they name a model only beside a version
    /// their own names use (`versions`), or in a question about a model's cost or making.
    static let ambiguous: Set<String> = {_set(AMBIGUOUS_FAMILY_WORDS)}
    /// The tokens the registry's names put right after an ambiguous family word.
    static let versions: [String: Set<String>] = {_versions()}
}}
"""


if __name__ == "__main__":
    SWIFT.write_text(render(), encoding="utf-8")
    print(f"wrote {SWIFT}")
