"""Write `ios/ModelRanking/Engine/ModelFamilies.swift` from the engine's registry (#206, M21-W2).

A comparison of model names ("nemotron mu glm mi") is a general question; the names come from the
registry, not a hand-kept list. `tests/unit/test_model_families.py` holds the written file equal to it.
(#194's use of them in the fact doubt was taken out after three verdicts, D-191.) Run after a change to the registry's families or display names:

    .venv/bin/python scripts/model_family_words.py
"""

from __future__ import annotations

import pathlib

from app.workflows.registry import family_words

SWIFT = pathlib.Path(__file__).resolve().parents[1] / "ios/ModelRanking/Engine/ModelFamilies.swift"


def _set(words: frozenset[str]) -> str:
    items = sorted(words)
    lines, line = [], "       "
    for item in items:
        piece = f' "{item}",'
        if len(line) + len(piece) > 110:
            lines.append(line)
            line = "       "
        line += piece
    lines.append(line)
    return "[\n" + "\n".join(lines) + "\n    ]"


def render() -> str:
    """The Swift file, as this registry would write it."""
    return f"""//  ModelFamilies.swift -- the family words of the models the engine ranks (#206, M21-W2).
//
//  GENERATED by `scripts/model_family_words.py` from `app.workflows.registry`; do not edit by hand.
//  `tests/unit/test_model_families.py` holds this file equal to the registry.

enum ModelFamilies {{
    /// Every family word the registry names a ranked model by, in plain lower case: what a comparison of
    /// model names reads (`CategoryHints.comparesModelsOnly`, #206).
    static let words: Set<String> = {_set(family_words())}
}}
"""


if __name__ == "__main__":
    SWIFT.write_text(render(), encoding="utf-8")
    print(f"wrote {SWIFT}")
