"""The sentence is DERIVED from the fact, and the fact is the truth. D-136, M12-W4.

Asked for Turkish, the obvious reading was a string file in the app. The measurement said
otherwise: every sentence on screen is generated by the engine, in English. Eleven milestones of
localisation debt with nothing to reveal it, because there was no second language.

D-136's answer is that `/v1` publishes the FACTS behind each sentence and the client writes the
sentence — in either language, from the same values. The English prose stays, derived from those
values, so no consumer breaks.

**The rule these tests hold is the one that makes it a single source of truth rather than two
copies:** every number the sentence quotes must appear in the fact. A fact that omits a value the
prose states is two sources again, and the second one drifts.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

#: W-108: reads the built artifact; skipped by name where it is absent (tests/conftest.py).
pytestmark = pytest.mark.artifact

REASONS = {"highest_score", "cheapest_within_window", "cheapest_above_floor", "nothing_clears_floor",
           "no_floor_measured"}


@pytest.fixture
def client(monkeypatch: pytest.MonkeyPatch) -> TestClient:
    monkeypatch.setenv("MODEL_RANKING_DB", "advisor.db")
    monkeypatch.setenv("APP_ENV", "test")
    from app.adapter import main as adapter

    return TestClient(adapter.app)


def _picks(client: TestClient, task: str, budget: str) -> list[dict]:
    answers = client.get(
        "/v1/recommendations", params={"task": task, "budget": budget}
    ).json()["answers"]
    return [pick for answer in answers for pick in answer["picks"]]


ALL = [(t, b) for t in ("coding", "assistant", "everyday", "expert", "mathematics")
       for b in ("low", "medium", "unlimited")]


@pytest.mark.parametrize("task,budget", ALL)
def test_every_pick_carries_a_fact_for_its_sentence(client: TestClient, task: str, budget: str) -> None:
    for pick in _picks(client, task, budget):
        assert pick.get("why_fact"), f"{pick['label']} has prose and no fact"
        assert pick["why_fact"]["reason"] in REASONS, pick["why_fact"]
        # A trade-off is optional; a trade-off WITHOUT its fact is not.
        if pick.get("trade_off"):
            assert pick.get("trade_off_fact"), (
                f"{pick['label']} states a trade-off in prose that a client cannot re-say"
            )


@pytest.mark.parametrize("task,budget", ALL)
def test_every_number_the_sentence_quotes_is_in_the_fact(
    client: TestClient, task: str, budget: str
) -> None:
    """**The test that makes this one source of truth instead of two.**

    If the prose quotes a number the fact does not carry, a client composing from the fact writes a
    different sentence — and the drift is silent, because both halves are internally consistent.
    That is the shape the M11 council found a dozen times.
    """
    for pick in _picks(client, task, budget):
        for field, fact_key in (("why", "why_fact"), ("trade_off", "trade_off_fact")):
            prose, fact = pick.get(field), pick.get(fact_key)
            if not prose or not fact:
                continue
            in_fact = {
                f"{value:g}" for value in fact.values() if isinstance(value, (int, float))
            }
            quoted = set(re.findall(r"\d+(?:\.\d+)?", prose))
            missing = {
                number for number in quoted
                if number not in in_fact and f"{float(number):g}" not in in_fact
            }
            assert not missing, (
                f"{pick['label']}.{field} quotes {sorted(missing)} which {fact_key} does not "
                f"carry — a client composing from the fact writes a different sentence.\n"
                f"  prose: {prose}\n  fact:  {fact}"
            )


def test_the_reason_distinguishes_the_two_budget_pick_cases(client: TestClient) -> None:
    """`cheapest_above_floor` and `nothing_clears_floor` are different answers wearing one label.

    The prose already distinguishes them — one begins "WARNING" — and a client that could not tell
    them apart would translate a warning as a recommendation.
    """
    reasons = set()
    for task in ("coding", "assistant", "everyday", "expert", "mathematics", "abstract"):
        for budget in ("low", "medium", "unlimited"):
            for pick in _picks(client, task, budget):
                if pick["label"] == "budget_pick":
                    reasons.add(pick["why_fact"]["reason"])

    # `no_floor_measured` (M17-W1): a surface whose own board is empty -- D-156 can publish one.
    assert reasons <= {"cheapest_above_floor", "nothing_clears_floor", "no_floor_measured"}, reasons
    assert reasons, "no budget pick was produced at all — the fixture proves nothing"


def test_a_fact_never_arrives_without_the_prose_it_explains(client: TestClient) -> None:
    """The other direction. A fact with no sentence means the English consumer lost its answer,
    which is the regression D-136's 'additive' promise exists to prevent."""
    for pick in _picks(client, "coding", "unlimited"):
        assert pick.get("why"), f"{pick['label']} has a fact and no sentence"


def test_the_facts_are_json_and_carry_no_engine_objects(client: TestClient) -> None:
    """Fixture blindness guard, and a contract point: a fact must be readable by a client that
    knows nothing about this engine's types."""
    for pick in _picks(client, "everyday", "low"):
        for value in pick["why_fact"].values():
            assert isinstance(value, (str, int, float, type(None))), value


def test_the_shipped_artifact_is_what_was_measured(client: TestClient) -> None:
    """These tests read the REPOSITORY's artifact, which a refresh republishes every twelve hours.
    If it is missing, every parametrised case above passes vacuously on an empty picks list."""
    assert Path("advisor.db").is_file()
    assert _picks(client, "coding", "unlimited"), "no picks: the assertions above tested nothing"
